<?php
// GENERATED by bump_version
return [
    'master_branch' => 'master',
    'develop_branch' => 'develop',
    'version_file' => __DIR__ . '/VERSION',
    'define_version_file' => __DIR__ . '/src/version.php', // you can add a 'PHP accessible' define with the current version
    'define_version_name' => 'CRUD_SUGAR_VERSION', // the define name
    'changelog_file' => __DIR__ . '/CHANGELOG', // A basic CHANGELOG
    'release_branches' => ['hotfix' => 'hotfix-*', 'release' => 'release-*', 'develop' => 'develop'], // The branches you should release on
];
